//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace livenlup1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour_()
        {
            this.hotels = new HashSet<hotel>();
            this.Types = new HashSet<Type>();
        }
    
        public int id { get; set; }
        public Nullable<int> tickestcount { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte[] imagepreview { get; set; }
        public Nullable<decimal> price { get; set; }
        public bool isactual { get; set; }

        public string ActualText
        {
            get
            {
                return (isactual) ? "Актуален" : "Завершен";
             }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hotel> hotels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type> Types { get; set; }
    }
}
